/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js');
goog.exportSymbol('proto.fun.dodo.tools.meta.EchoList', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fun.dodo.tools.meta.EchoList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.fun.dodo.tools.meta.EchoList.repeatedFields_, null);
};
goog.inherits(proto.fun.dodo.tools.meta.EchoList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.fun.dodo.tools.meta.EchoList.displayName = 'proto.fun.dodo.tools.meta.EchoList';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.fun.dodo.tools.meta.EchoList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fun.dodo.tools.meta.EchoList.prototype.toObject = function(opt_includeInstance) {
  return proto.fun.dodo.tools.meta.EchoList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fun.dodo.tools.meta.EchoList} msg The msg instance to transform.
 * @return {!Object}
 */
proto.fun.dodo.tools.meta.EchoList.toObject = function(includeInstance, msg) {
  var f, obj = {
    objectList: jspb.Message.toObjectList(msg.getObjectList(),
    google_protobuf_any_pb.Any.toObject, includeInstance),
    count: jspb.Message.getFieldWithDefault(msg, 2, 0),
    index: jspb.Message.getFieldWithDefault(msg, 3, 0),
    size: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fun.dodo.tools.meta.EchoList}
 */
proto.fun.dodo.tools.meta.EchoList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fun.dodo.tools.meta.EchoList;
  return proto.fun.dodo.tools.meta.EchoList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fun.dodo.tools.meta.EchoList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fun.dodo.tools.meta.EchoList}
 */
proto.fun.dodo.tools.meta.EchoList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_any_pb.Any;
      reader.readMessage(value,google_protobuf_any_pb.Any.deserializeBinaryFromReader);
      msg.addObject(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCount(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setIndex(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSize(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fun.dodo.tools.meta.EchoList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fun.dodo.tools.meta.EchoList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fun.dodo.tools.meta.EchoList} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.fun.dodo.tools.meta.EchoList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getObjectList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
  f = message.getCount();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getIndex();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getSize();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
};


/**
 * repeated google.protobuf.Any object = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.google.protobuf.Any>}
 */
proto.fun.dodo.tools.meta.EchoList.prototype.getObjectList = function() {
  return /** @type{!Array.<!proto.google.protobuf.Any>} */ (
    jspb.Message.getRepeatedWrapperField(this, google_protobuf_any_pb.Any, 1));
};


/** @param {!Array.<!proto.google.protobuf.Any>} value */
proto.fun.dodo.tools.meta.EchoList.prototype.setObjectList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.google.protobuf.Any=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.protobuf.Any}
 */
proto.fun.dodo.tools.meta.EchoList.prototype.addObject = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.google.protobuf.Any, opt_index);
};


proto.fun.dodo.tools.meta.EchoList.prototype.clearObjectList = function() {
  this.setObjectList([]);
};


/**
 * optional uint32 count = 2;
 * @return {number}
 */
proto.fun.dodo.tools.meta.EchoList.prototype.getCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.fun.dodo.tools.meta.EchoList.prototype.setCount = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional uint32 index = 3;
 * @return {number}
 */
proto.fun.dodo.tools.meta.EchoList.prototype.getIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.fun.dodo.tools.meta.EchoList.prototype.setIndex = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional uint32 size = 4;
 * @return {number}
 */
proto.fun.dodo.tools.meta.EchoList.prototype.getSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.fun.dodo.tools.meta.EchoList.prototype.setSize = function(value) {
  jspb.Message.setField(this, 4, value);
};


goog.object.extend(exports, proto.fun.dodo.tools.meta);
